# Generated by Django 4.2.3 on 2023-09-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0003_reportmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='isReported',
            field=models.BooleanField(default=False, verbose_name='Hesap şikayet edildi mi'),
        ),
    ]
