# Generated by Django 4.2.3 on 2023-09-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0004_bloguser_isreported'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmanagement',
            name='reportMessage',
            field=models.TextField(default='Şikayet Nedeninizi Buraya Yaziniz', verbose_name='Sebep:'),
        ),
        migrations.AlterField(
            model_name='reportmanagement',
            name='reportReason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='QuickMsg_app.tinkspost', verbose_name='Şikayet Sebebi:'),
        ),
    ]
