# Generated by Django 4.2.3 on 2023-10-01 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0005_reportmanagement_reportmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmanagement',
            name='reportReason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='QuickMsg_app.tinkspost', verbose_name='Şikayet Edilen Tweet:'),
        ),
        migrations.CreateModel(
            name='BanUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banReason', models.CharField(max_length=50, verbose_name='Sebep:')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('authorizedPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetkili', to=settings.AUTH_USER_MODEL, verbose_name='Banlayan:')),
                ('bannedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Banlanan User:')),
            ],
        ),
    ]
