# Generated by Django 4.2.3 on 2023-10-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0006_alter_reportmanagement_reportreason_banuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banuser',
            name='banReason',
            field=models.TextField(max_length=100, verbose_name='Sebep:'),
        ),
    ]
