# Generated by Django 4.2.3 on 2023-10-01 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0008_alter_banuser_banreason_removeban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removeban',
            name='authorizedUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized', to=settings.AUTH_USER_MODEL, verbose_name='Bani Kaldiran Yetkili:'),
        ),
    ]
