# Generated by Django 4.2.3 on 2023-10-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0011_liketweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liketweet',
            options={'verbose_name': 'Beğeni', 'verbose_name_plural': 'Beğenilen Tweetler'},
        ),
    ]
