# Generated by Django 4.2.3 on 2023-10-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickMsg_app', '0012_alter_liketweet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinkspost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_like', to='QuickMsg_app.liketweet'),
        ),
    ]
